import type { Deal, Client, Contact, BD, Notification, BDDashboard, ExecutiveDashboard, LeaderboardEntry } from './types/index';

export const MOCK_BDS: BD[] = [
  {
    id: 'bd-001',
    firstName: 'Henne',
    lastName: 'Santos',
    email: 'henne@company.com',
    role: 'BD_REP',
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2025-12-01',
  },
  {
    id: 'bd-002',
    firstName: 'Isten',
    lastName: 'Cruz',
    email: 'isten@company.com',
    role: 'BD_REP',
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2025-12-01',
  },
  {
    id: 'bd-003',
    firstName: 'Brian',
    lastName: 'Reyes',
    email: 'brian@company.com',
    role: 'BD_REP',
    isActive: true,
    createdAt: '2024-09-01',
    updatedAt: '2025-12-01',
  },
  {
    id: 'bd-mgr',
    firstName: 'Maria',
    lastName: 'Villanueva',
    email: 'maria@company.com',
    role: 'SALES_MANAGER',
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2025-12-01',
  },
];

export const MOCK_CLIENTS: Client[] = [
  { id: 'c-001', name: 'TechCorp Philippines', brand: 'TechCorp', account_type: 'Enterprise', status: 'Active', industry: { id: 'ind-1', name: 'Technology & IT' } },
  { id: 'c-002', name: 'Globe Fintech Inc', brand: 'GlobeFin', account_type: 'Corporate', status: 'Active', industry: { id: 'ind-2', name: 'Financial Services' } },
  { id: 'c-003', name: 'Metro Retail Group', account_type: 'SMB', status: 'Active', industry: { id: 'ind-3', name: 'Retail & E-commerce' } },
  { id: 'c-004', name: 'PhilHealth Corporation', account_type: 'Government', status: 'Prospect', industry: { id: 'ind-4', name: 'Government' } },
  { id: 'c-005', name: 'ABS Media Holdings', account_type: 'Enterprise', status: 'Active', industry: { id: 'ind-5', name: 'Media & Entertainment' } },
  { id: 'c-006', name: 'Ayala Land Realty', account_type: 'Corporate', status: 'Active', industry: { id: 'ind-6', name: 'Real Estate' } },
  { id: 'c-007', name: 'SM Supermalls Co.', account_type: 'Enterprise', status: 'Active', industry: { id: 'ind-3', name: 'Retail & E-commerce' } },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd-001',
    deal_name: 'TechCorp - MEDIAWATCH',
    monthly_subscription: 85000,
    revenue: 1020000,
    duration: 12,
    stage: 'Closed Won',
    stage_id: 's-6',
    is_closed: true,
    remarks: 'Strong relationship with CTO. Upsell opportunity for LOCOBUZZ next quarter.',
    action_plan: 'Schedule QBR for March 2026',
    proposal_revision_count: 2,
    lead_source: 'Outbound',
    sales_cycle_days: 45,
    start_date: '2025-10-01',
    due_date: '2025-11-30',
    closed_date: '2025-11-14',
    last_stage_update_at: '2025-11-14',
    bd_id: 'bd-001',
    client_id: 'c-001',
    service_id: 'svc-1',
    probability_pct: 100,
    days_in_stage: 0,
    bd: MOCK_BDS[0],
    client: MOCK_CLIENTS[0],
  },
  {
    id: 'd-002',
    deal_name: 'Globe Fintech - LOCOBUZZ',
    monthly_subscription: 120000,
    revenue: 1440000,
    duration: 12,
    stage: 'Negotiation',
    stage_id: 's-5',
    is_closed: false,
    remarks: 'Legal review ongoing. CFO bought in, waiting for final approval.',
    action_plan: 'Follow up with legal team on contract redlines',
    proposal_revision_count: 3,
    lead_source: 'Inbound',
    start_date: '2025-11-01',
    due_date: '2026-03-15',
    last_stage_update_at: '2026-02-20',
    action_plan_due_date: '2026-03-05',
    bd_id: 'bd-001',
    client_id: 'c-002',
    service_id: 'svc-2',
    probability_pct: 75,
    days_in_stage: 10,
    bd: MOCK_BDS[0],
    client: MOCK_CLIENTS[1],
  },
  {
    id: 'd-003',
    deal_name: 'Metro Retail - SHAREDVIEW',
    monthly_subscription: 45000,
    revenue: 540000,
    duration: 12,
    stage: 'Proposal Sent',
    stage_id: 's-4',
    is_closed: false,
    remarks: 'GM is interested in real-time analytics. Budget approved.',
    action_plan: 'Send revised proposal with enhanced reporting module',
    proposal_revision_count: 1,
    lead_source: 'Referral',
    start_date: '2026-01-15',
    due_date: '2026-03-30',
    last_stage_update_at: '2026-02-15',
    action_plan_due_date: '2026-03-08',
    bd_id: 'bd-001',
    client_id: 'c-003',
    service_id: 'svc-3',
    probability_pct: 60,
    days_in_stage: 15,
    bd: MOCK_BDS[0],
    client: MOCK_CLIENTS[2],
  },
  {
    id: 'd-004',
    deal_name: 'PhilHealth - MEDIAWATCH',
    monthly_subscription: 65000,
    revenue: 780000,
    duration: 12,
    stage: 'Discovery',
    stage_id: 's-3',
    is_closed: false,
    remarks: 'Initial meeting went well. Director keen on social monitoring.',
    action_plan: 'Submit RFP response by March 10',
    proposal_revision_count: 0,
    lead_source: 'Inbound',
    start_date: '2026-02-01',
    due_date: '2026-04-30',
    last_stage_update_at: '2026-02-25',
    action_plan_due_date: '2026-03-10',
    bd_id: 'bd-002',
    client_id: 'c-004',
    service_id: 'svc-1',
    probability_pct: 40,
    days_in_stage: 5,
    bd: MOCK_BDS[1],
    client: MOCK_CLIENTS[3],
  },
  {
    id: 'd-005',
    deal_name: 'ABS Media - Bundle (MEDIAWATCH + LOCOBUZZ)',
    monthly_subscription: 150000,
    revenue: 1800000,
    duration: 12,
    stage: 'Negotiation',
    stage_id: 's-5',
    is_closed: false,
    remarks: 'VP Operations pushing for Q1 deployment. Good fit for their monitoring needs.',
    action_plan: 'Final commercial terms call scheduled March 7',
    proposal_revision_count: 2,
    lead_source: 'Outbound',
    start_date: '2025-12-01',
    due_date: '2026-03-31',
    last_stage_update_at: '2026-02-18',
    action_plan_due_date: '2026-03-07',
    bd_id: 'bd-001',
    client_id: 'c-005',
    bundle_id: 'b-001',
    probability_pct: 75,
    days_in_stage: 12,
    bd: MOCK_BDS[0],
    client: MOCK_CLIENTS[4],
  },
  {
    id: 'd-006',
    deal_name: 'Ayala Land - REPORTS',
    monthly_subscription: 30000,
    revenue: 360000,
    duration: 12,
    stage: 'Closed Lost',
    stage_id: 's-7',
    is_closed: true,
    remarks: 'Lost to competitor on pricing. Their product offered lower monthly fees.',
    action_plan: 'Re-engage in Q3 2026 when contract expires',
    proposal_revision_count: 4,
    lead_source: 'Outbound',
    final_proposed_value: 25000,
    sales_cycle_days: 90,
    start_date: '2025-09-01',
    due_date: '2025-12-31',
    closed_date: '2025-12-28',
    last_stage_update_at: '2025-12-28',
    bd_id: 'bd-002',
    client_id: 'c-006',
    service_id: 'svc-4',
    probability_pct: 0,
    days_in_stage: 0,
    bd: MOCK_BDS[1],
    client: MOCK_CLIENTS[5],
  },
  {
    id: 'd-007',
    deal_name: 'SM Supermalls - LOCOBUZZ',
    monthly_subscription: 200000,
    revenue: 2400000,
    duration: 12,
    stage: 'Inquiry',
    stage_id: 's-1',
    is_closed: false,
    remarks: 'Warm lead from LinkedIn. Head of Digital very responsive.',
    action_plan: 'Schedule discovery call for March 10',
    proposal_revision_count: 0,
    lead_source: 'Inbound',
    start_date: '2026-02-28',
    due_date: '2026-06-30',
    last_stage_update_at: '2026-02-28',
    action_plan_due_date: '2026-03-10',
    bd_id: 'bd-003',
    client_id: 'c-007',
    service_id: 'svc-2',
    probability_pct: 10,
    days_in_stage: 2,
    bd: MOCK_BDS[2],
    client: MOCK_CLIENTS[6],
  },
  {
    id: 'd-008',
    deal_name: 'TechCorp - LOCOBUZZ (Upsell)',
    monthly_subscription: 95000,
    revenue: 1140000,
    duration: 12,
    stage: 'Prospecting',
    stage_id: 's-2',
    is_closed: false,
    remarks: 'Existing client. CTO mentioned interest during QBR.',
    action_plan: 'Send LOCOBUZZ product deck and case studies',
    proposal_revision_count: 0,
    lead_source: 'Outbound',
    start_date: '2026-02-15',
    due_date: '2026-05-31',
    last_stage_update_at: '2026-02-28',
    action_plan_due_date: '2026-03-05',
    bd_id: 'bd-001',
    client_id: 'c-001',
    service_id: 'svc-2',
    probability_pct: 20,
    days_in_stage: 15,
    bd: MOCK_BDS[0],
    client: MOCK_CLIENTS[0],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-001',
    content: 'Deal "TechCorp - LOCOBUZZ (Upsell)" has been in Prospecting for 15 days (target: 3 days)',
    type: 'DealStuck',
    is_read: false,
    triggered_by: 'DaysInStageExceeded',
    created_at: '2026-03-02T08:00:00',
    bd_id: 'bd-001',
    deal_id: 'd-008',
  },
  {
    id: 'n-002',
    content: 'Action plan due: Follow up with legal team on contract redlines — Globe Fintech - LOCOBUZZ',
    type: 'ActionPlanDue',
    is_read: false,
    triggered_by: 'ActionPlanPassed',
    created_at: '2026-03-02T08:00:00',
    bd_id: 'bd-001',
    deal_id: 'd-002',
  },
  {
    id: 'n-003',
    content: 'Deal "Metro Retail - SHAREDVIEW" has been in Proposal Sent for 15 days (target: 3 days)',
    type: 'DealStuck',
    is_read: false,
    triggered_by: 'DaysInStageExceeded',
    created_at: '2026-03-02T08:00:00',
    bd_id: 'bd-001',
    deal_id: 'd-003',
  },
  {
    id: 'n-004',
    content: 'Stage updated: Globe Fintech - LOCOBUZZ moved to Negotiation',
    type: 'StageChange',
    is_read: true,
    triggered_by: 'StageChange',
    created_at: '2026-02-20T14:32:00',
    bd_id: 'bd-001',
    deal_id: 'd-002',
  },
  {
    id: 'n-005',
    content: 'New deal assigned: SM Supermalls - LOCOBUZZ',
    type: 'NewDealAssigned',
    is_read: true,
    triggered_by: 'StageChange',
    created_at: '2026-02-28T09:00:00',
    bd_id: 'bd-003',
    deal_id: 'd-007',
  },
];

export const MOCK_BD_DASHBOARD: BDDashboard = {
  bd: MOCK_BDS[0],
  quarter: 'Q1 2026',
  quarter_range: 'Jan 1 – Mar 31',
  deals_closed: 1,
  open_deals: 4,
  total_target_status_pct: 22.4,
  sales_forecast: 2588162,
  sales_variance: 5431838,
  monthly_excess_deficit: -1831838,
  quarterly_excess_deficit: -5431838,
  quota_quarterly: 7000000,
  actual_closed_quarterly: 1568162,
  top_deals: MOCK_DEALS.slice(0, 3),
  pipeline_deals: MOCK_DEALS.filter(d => d.bd_id === 'bd-001' && !d.is_closed),
  stuck_deals: MOCK_DEALS.filter(d => (d.days_in_stage || 0) > 3 && d.bd_id === 'bd-001'),
};

export const PIPELINE_STAGES = [
  { id: 's-1', name: 'Inquiry' as const, duration: 3, probability: 10, color: '#4a4f6b' },
  { id: 's-2', name: 'Prospecting' as const, duration: 3, probability: 20, color: '#4f6ef7' },
  { id: 's-3', name: 'Discovery' as const, duration: 3, probability: 40, color: '#10b981' },
  { id: 's-4', name: 'Proposal Sent' as const, duration: 3, probability: 60, color: '#8b5cf6' },
  { id: 's-5', name: 'Negotiation' as const, duration: 3, probability: 75, color: '#f59e0b' },
  { id: 's-6', name: 'Closed Won' as const, duration: null, probability: 100, color: '#10b981' },
  { id: 's-7', name: 'Closed Lost' as const, duration: null, probability: 0, color: '#f43f5e' },
];

export const INDUSTRIES = [
  'Technology & IT', 'Financial Services', 'Healthcare', 'Retail & E-commerce',
  'Manufacturing', 'Telecommunications', 'Media & Entertainment', 'Professional Services',
  'Government', 'Education', 'Real Estate', 'Hospitality & Tourism', 'Other',
];

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  { rank: 1, bd: MOCK_BDS[0], closed_revenue: 1568162, quota: 7000000, attainment_pct: 22.4, deals_won: 1, win_rate: 83 },
  { rank: 2, bd: MOCK_BDS[1], closed_revenue: 390000, quota: 7000000, attainment_pct: 5.6, deals_won: 0, win_rate: 0 },
  { rank: 3, bd: MOCK_BDS[2], closed_revenue: 0, quota: 7000000, attainment_pct: 0, deals_won: 0, win_rate: 0 },
];

export const PIPELINE_BY_STAGE = [
  { stage: 'Inquiry', deal_count: 1, total_value: 2400000, weighted_value: 240000 },
  { stage: 'Prospecting', deal_count: 1, total_value: 1140000, weighted_value: 228000 },
  { stage: 'Discovery', deal_count: 1, total_value: 780000, weighted_value: 312000 },
  { stage: 'Proposal Sent', deal_count: 1, total_value: 540000, weighted_value: 324000 },
  { stage: 'Negotiation', deal_count: 2, total_value: 3240000, weighted_value: 2430000 },
  { stage: 'Closed Won', deal_count: 1, total_value: 1568162, weighted_value: 1568162 },
  { stage: 'Closed Lost', deal_count: 1, total_value: 360000, weighted_value: 0 },
];

export const MOCK_SERVICES = [
  { id: 'svc-1', name: 'MEDIAWATCH', description: 'Media monitoring and analytics platform', is_active: true },
  { id: 'svc-2', name: 'LOCOBUZZ', description: 'Social media listening and engagement', is_active: true },
  { id: 'svc-3', name: 'SHAREDVIEW', description: 'Shared analytics and reporting dashboard', is_active: true },
  { id: 'svc-4', name: 'REPORTS', description: 'Custom reporting and insights service', is_active: true },
];

export const MOCK_BUNDLES = [
  {
    id: 'b-001',
    name: 'Media Suite',
    services: [
      { service_id: 'svc-1', bundle_id: 'b-001', name: 'MEDIAWATCH', service_value: 80000, revenue_share_pct: 50 },
      { service_id: 'svc-2', bundle_id: 'b-001', name: 'LOCOBUZZ', service_value: 80000, revenue_share_pct: 50 },
    ],
  },
  {
    id: 'b-002',
    name: 'Analytics Pack',
    services: [
      { service_id: 'svc-3', bundle_id: 'b-002', name: 'SHAREDVIEW', service_value: 40000, revenue_share_pct: 40 },
      { service_id: 'svc-4', bundle_id: 'b-002', name: 'REPORTS', service_value: 60000, revenue_share_pct: 60 },
    ],
  },
  {
    id: 'b-003',
    name: 'Full Stack',
    services: [
      { service_id: 'svc-1', bundle_id: 'b-003', name: 'MEDIAWATCH', service_value: 75000, revenue_share_pct: 25 },
      { service_id: 'svc-2', bundle_id: 'b-003', name: 'LOCOBUZZ', service_value: 75000, revenue_share_pct: 25 },
      { service_id: 'svc-3', bundle_id: 'b-003', name: 'SHAREDVIEW', service_value: 75000, revenue_share_pct: 25 },
      { service_id: 'svc-4', bundle_id: 'b-003', name: 'REPORTS', service_value: 75000, revenue_share_pct: 25 },
    ],
  },
];

export const MOCK_CONTACTS: import('./types').Contact[] = [
  { id: 'con-001', first_name: 'Ricardo', last_name: 'Santos', email: 'rsantos@techcorp.ph', number: '+63 917 111 0001', designation: 'Chief Technology Officer', decision_rank: 'Tier 1 Economic Buyer', is_primary: true, client_id: 'c-001' },
  { id: 'con-002', first_name: 'Ana', last_name: 'Reyes', email: 'areyes@techcorp.ph', number: '+63 917 111 0002', designation: 'IT Director', decision_rank: 'Tier 2 Decision Maker', is_primary: false, client_id: 'c-001' },
  { id: 'con-003', first_name: 'Jose', last_name: 'Cruz', email: 'jcruz@globefin.ph', number: '+63 917 222 0001', designation: 'CFO', decision_rank: 'Tier 1 Economic Buyer', is_primary: true, client_id: 'c-002' },
  { id: 'con-004', first_name: 'Maria', last_name: 'Lim', email: 'mlim@metroretail.ph', designation: 'General Manager', decision_rank: 'Tier 2 Decision Maker', is_primary: true, client_id: 'c-003' },
  { id: 'con-005', first_name: 'Roberto', last_name: 'Dela Cruz', email: 'rdelacruz@philhealth.gov.ph', designation: 'Director', decision_rank: 'Tier 1 Economic Buyer', is_primary: true, client_id: 'c-004' },
  { id: 'con-006', first_name: 'Sandra', last_name: 'Villanueva', email: 'svillaneva@abs.ph', number: '+63 917 555 0001', designation: 'VP Operations', decision_rank: 'Tier 1 Economic Buyer', is_primary: true, client_id: 'c-005' },
  { id: 'con-007', first_name: 'Miguel', last_name: 'Torres', email: 'mtorres@abs.ph', designation: 'Marketing Manager', decision_rank: 'Tier 3 Influencer', is_primary: false, client_id: 'c-005' },
];
